name: Update YouTube Player Script

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"   # every hour

permissions:
  contents: write
  pull-requests: write

jobs:
  check-player:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install UV & deps
        run: |
          pip install uv
          uv sync

      - name: Snapshot before (dirs only)
        run: |
          find . -maxdepth 1 -mindepth 1 -type d -not -path "*/\.*" -printf "%f\n" | sort > before.txt

      - name: Fetch and build JS
        run: uv run workflow.py

      - name: Snapshot after (dirs only)
        run: |
          find . -maxdepth 1 -mindepth 1 -type d -not -path "*/\.*" -printf "%f\n" | sort > after.txt

      - name: Detect new directory
        id: detect
        run: |
          NEW_DIR=$(comm -13 before.txt after.txt | head -n1)
          if [ -z "$NEW_DIR" ]; then
            echo "skip=true" >> $GITHUB_OUTPUT
            exit 0
          fi
          echo "player_id=$NEW_DIR" >> $GITHUB_OUTPUT

      - name: Skip if nothing new
        if: steps.detect.outputs.skip == 'true'
        run: echo "Nothing to update."

      - name: Configure Git
        if: steps.detect.outputs.skip != 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create branch and commit changes
        if: steps.detect.outputs.skip != 'true'
        run: |
          PLAYER=${{ steps.detect.outputs.player_id }}
          BRANCH="update-player-$PLAYER"

          # fetch & checkout existing branch or start new from main
          git fetch origin "$BRANCH" || true
          git checkout "$BRANCH" || git checkout -b "$BRANCH" origin/main

          rm -f before.txt after.txt
          git add -f "$PLAYER"
          git commit -m "chore: update YouTube player script for $PLAYER" || echo "→ no changes to commit"
          git push --set-upstream origin HEAD:"$BRANCH"

      - name: Create or update Pull Request
        if: steps.detect.outputs.skip != 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: update-player-${{ steps.detect.outputs.player_id }}
          title: "Update player script: ${{ steps.detect.outputs.player_id }}"
          commit-message: "chore: update YouTube player script for ${{ steps.detect.outputs.player_id }}"
          body: |
            This PR updates the YouTube decryption script for player ID `${{ steps.detect.outputs.player_id }}`.
            - Generated on run ID `${{ github.run_id }}`
            - Includes the new `base.js` bundle.
          labels: automated
